"""todos: add user_id column

Revision ID: 4b00560fceb7
Revises: d5caf946ba43
Create Date: 2025-11-14 00:20:38.426574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4b00560fceb7"
down_revision: Union[str, Sequence[str], None] = "d5caf946ba43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("todos", sa.Column("user_id", sa.Uuid(), nullable=True))

  # Set a default user_id for existing records (this should be replaced with actual user IDs
  op.execute("UPDATE todos SET user_id = '7fd0b380-4d6e-41a9-b376-33527987467c' WHERE user_id IS NULL")
  op.alter_column("todos", "user_id", nullable=False)

  op.alter_column(
    "todos",
    "created_at",
    existing_type=postgresql.TIMESTAMP(),
    type_=sa.TIMESTAMP(timezone=True),
    existing_nullable=False,
  )
  op.alter_column(
    "todos",
    "updated_at",
    existing_type=postgresql.TIMESTAMP(),
    type_=sa.TIMESTAMP(timezone=True),
    existing_nullable=False,
  )
  op.alter_column(
    "todos",
    "completed_at",
    existing_type=postgresql.TIMESTAMP(),
    type_=sa.TIMESTAMP(timezone=True),
    existing_nullable=True,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "todos",
    "completed_at",
    existing_type=sa.TIMESTAMP(timezone=True),
    type_=postgresql.TIMESTAMP(),
    existing_nullable=True,
  )
  op.alter_column(
    "todos",
    "updated_at",
    existing_type=sa.TIMESTAMP(timezone=True),
    type_=postgresql.TIMESTAMP(),
    existing_nullable=False,
  )
  op.alter_column(
    "todos",
    "created_at",
    existing_type=sa.TIMESTAMP(timezone=True),
    type_=postgresql.TIMESTAMP(),
    existing_nullable=False,
  )
  op.drop_column("todos", "user_id")
  # ### end Alembic commands ###
