"""initial setup: created todos' table

Revision ID: d5caf946ba43
Revises:
Create Date: 2025-11-13 20:35:16.884103

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5caf946ba43"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "todos",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("completed", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("completed_at", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("todos")
  # ### end Alembic commands ###
